import type { Metadata } from "next"
import { Comfortaa, Nunito } from "next/font/google"
import "./globals.css"
import { ReactNode } from "react"
import { Header } from "@/components/widgets"
import QueryProvider from "@/providers/QueryProvider"

const comfortaa = Comfortaa({
	subsets: ["latin", "cyrillic"],
	variable: "--font-comfortaa",
	display: "swap"
})

const nunito = Nunito({
	subsets: ["latin", "cyrillic"],
	variable: "--font-nunito",
	display: "swap"
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="ru" className={`${comfortaa.variable} ${nunito.variable}`}>
			<body>
				<Header />

				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	)
}
